version: "3.9"

services:

  forum123-app:
    container_name: forum123-app
    build: &forum123-app-build
      context: ../..  # path from the current file to the project root directory
      dockerfile: envs/prod/Dockerfile  # path from the project root directory to the Dockerfile
    env_file:
      - .env
    depends_on:
      forum123-db:
        condition: service_healthy
    entrypoint: >
      bash -c "
        alembic upgrade head
        gunicorn --config=envs/prod/gunicorn/config.py
      "

  forum123-db:
    container_name: forum123-db
    image: postgres:15
    env_file:
      - .env
    healthcheck:
      # see: https://github.com/peter-evans/docker-compose-healthcheck#waiting-for-postgresql-to-be-healthy
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      retries: 10
    volumes:
      - forum123-prod-db:/var/lib/postgresql/data

  nginx:
    container_name: forum123-proxy
    image: nginx:1.23.3-alpine
    ports:
      - 80:8080
    depends_on:
      - forum123-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  forum123-prod-db:
    name: forum123-prod-db
